embeddings {
  tensor_name: "embedding:0"
  metadata_path: "/home/zelda/Jupyter Documents/PPT/tensor1.4/projector/projector/metadata.tsv"
  sprite {
    image_path: "/home/zelda/Jupyter Documents/PPT/tensor1.4/projector/data/Fashion_MNIST_sprites.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
